### ISSUE TITLE
Get Bittrex Fees and Coin Pairs

### ISSUE THREAD

**Issue by asperellis** [asperellis/albatross#6]
Add here so Alex can add to exchange file
Also get API limits while you're there <3

**Comment by adoti** [comment]
Bittrex fees = .25%

Bittrex API rate limit is discussed [here](https://bitcoin.stackexchange.com/questions/53778/bittrex-api-rate-limit). TLDR is that the limits aren't stated.  They say "if you're hitting the limit, you're abusing it..."  so I assume they mean if we're making so many calls that we're trying to disrupt their system then we're going to get banned but otherwise we're OK.

**Comment by adoti** [comment]
Redoing all coin pairs and assets in wallet to have a BTC pair in each exchange.  ETH pairing must be on at least one other exchange to be considered.

//POLONIEX:
//BTC pairings
LTCBTC
ETHBTC
DASHBTC
ETCBTC
LSKBTC
NAVBTC
OMGBTC
STORJBTC
STRATBTC
XMRBTC
XRPBTC
ZECBTC
//ETH pairings
ETCETH
LSKETH
OMGETH
ZECETH

//BINANCE:
//BTC pairings
LTCBTC
ETHBTC
DASHBTC
ETCBTC
LSKBTC
NAVBTC
OMGBTC
STORJBTC
STRATBTC
XMRBTC
XRPBTC
ZECBTC
//ETH pairings
LTCETH
DASHETH
ETCETH
LSKETH
OMGETH
STORJETH
STRATETH
XMRETH
XRPETH
ZECETH

//BITTREX:
//BTC pairings
LTCBTC
ETHBTC
DASHBTC
ETCBTC
LSKBTC
NAVBTC
OMGBTC
STORJBTC
STRATBTC
XMRBTC
XRPBTC
ZECBTC
//ETH pairings
LTCETH
DASHETH
ETCETH
OMGETH
STORJETH
STRATETH
XMRETH
XRPETH
ZECETH

//New Wallet:
BTC
LTC
ETH
DASH
ETC
LSK
NAV
OMG
STORJ
STRAT
XMR
XRP
ZEC

**Comment by adoti** [comment]
Removing BTS, GAS, ZRX from wallets and pairs.

**Comment by asperellis** [comment]
Added pairs and updated wallet to not have any of the removed ones
